version: '2'
services:
    web:
        build: .
        ports:
            - "8000:8000"
            - "80:80"
        depends_on:
            - db
        volumes:
            - .:/app
    db:
        image: mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
