version: '2'
services:
    web:
        build: .
        command: php -S 0.0.0.0:8000 - /app
        ports:
            - "8000:8000"
        depends_on:
            - db
        volumes:
            - .:/code
    db:
        image: mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
